# nginx proxy address - http://172.17.0.1:58064

name: docmost
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: docmost/docmost:latest
    container_name: docmost-app
    hostname: ${BASE_HOST_NAME:-localhost}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      REDIS_URL: redis://docmost-redis:6379
      APP_URL: https://${BASE_HOST_NAME:-localhost}
      APP_SECRET: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      DATABASE_URL: postgresql://${DB_USER_NAME:-docmost}:${DB_USER_PASS:-changeme_db_password}@docmost-db:5432/${DB_CREATE_DATABASE_NAME:-docmost}?schema=public
    ports:
      - "172.17.0.1:58064:3000"
    volumes:
      - "./volumes/data/docmost:/app/data/storage"
    depends_on:
      - db
      - redis
    networks:
      - docmost

  db:
    image: postgres:latest
    container_name: docmost-db
    hostname: docmost-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-docmost}
      POSTGRES_USER: ${DB_USER_NAME:-docmost}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - "./volumes/data/db/postgres/docmost:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - docmost

  redis:
    image: redis:alpine
    container_name: docmost-redis
    hostname: docmost-redis
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - "./volumes/data/db/redis/docmost:/data"
    networks:
      - docmost

networks:
  docmost:
    name: docmost
    external: false
